apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-server
  namespace: dev
spec:
  replicas:
  selector:
    matchLabels:
      app: redis

  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: uhub.service.ucloud.cn/oldxu/redis:6
    
